### ISSUE TITLE
VOACAP not updating when changing 'DX"

### ISSUE THREAD

**Issue by IzzyMan12078** [kj7rrv/hamclock#2]
After upgrade to 4.01 - VOACAP does not change at all when changing/setting different 'DX' locations - regardless of how the 'DX' is changed (map, POTA, SOAT, DXCLUSTER etc.)

Raspberry PI 4 / Latest RASPI OS.

**Comment by IzzyMan12078** [comment]
Contacted Developer - Didn't realize this was for AUR packages

**Comment by fang64** [comment]
> Contacted Developer - Didn't realize this was for AUR packages

No problem, yup contact them via https://clearskyinstitute.com/ham/HamClock/ 

I package this on both AUR/PACSTALL
